name: mask_vae
channels:
  - bioconda
  - pytorch
  - idr
  - ome
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - scipy
  - pytest
  - tqdm
  - pandas
  - tensorboard
  - flake8
  - python
  - future
  - jupyter
  - absl-py
  - pip
  - torchvision
  - matplotlib
  - pyyaml
  - click
  - black
  - rope
  - autopep8
  - pytorch
  - torchvision
  - numpy
  - torchaudio
  - pytorch-lightning
  - scikit-image
  - pytorch-model-summary
  - pyro-ppl
  - scikit-learn
