[tool.poetry]
name = "bio_vae"
version = "0.1.0"
description = ""
authors = ["Craig  <ctr26@ebi.ac.uk>"]

[tool.poetry.dependencies]
python = "3.8.13"
pip = "^22.2.2"
torchvision = "^0.13.1"
torch = "^1.12.1"
torchinfo = "^1.7.0"
matplotlib = "^3.5.3"
pytorch-lightning = "^1.7.5"
pyro-ppl = "^1.8.2"
scikit-image = "^0.19.3"
iteround = "^1.0.4"
ipykernel = "^6.15.2"
nonechucks = "^0.4.2"
pythae = "^0.0.8"


[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
