[tool.poetry]
name = "mask_vae"
version = "0.1.0"
description = ""
authors = ["Craig  <ctr26@ebi.ac.uk>"]

[tool.poetry.dependencies]
python = "3.8.8"
pytest = "^7.0.1"
torchvision = "^0.13.0"
torch = "^1.12.0"
torchinfo = "^1.7.0"
matplotlib = "^3.5.2"
pytorch-lightning = "^1.6.5"
pip = "^22.2.1"
pyro-ppl = "^1.8.1"
scikit-image = "^0.19.3"
scikit-learn = "^1.1.1"
iteround = "^1.0.4"
umap-learn = {extras = ["plot"], version = "^0.5.3"}
ipykernel = "^6.15.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
